### ISSUE TITLE
Missing Hunter abilities

### ISSUE THREAD

**Issue by CptShooter** [Rhykes/GladiatorlosSA2#3]
Hi,

I want to report missing some hunter abilities.
Addon version: 3.3
I think I saw them before. 

Missing abilities: 
- Trueshot
- Feign death

![obraz](https://user-images.githubusercontent.com/1506567/107879335-89462900-6ed8-11eb-8ab5-60e1caa9db29.png)
![obraz](https://user-images.githubusercontent.com/1506567/107879339-93682780-6ed8-11eb-9e8b-a9a594b910af.png)
![obraz](https://user-images.githubusercontent.com/1506567/107879348-99f69f00-6ed8-11eb-95c2-a22a286f2de4.png)
![obraz](https://user-images.githubusercontent.com/1506567/107879354-a24eda00-6ed8-11eb-87a9-65e2cd4ca2a1.png)

**Comment by Rhykes** [comment]
Sorry it took so long for me to see this.

I believe Trueshot should be fixed already (probably wasn't when you sent this, but just in case). It might not be displayed as Trueshot since other hunter spec's major cooldowns use the same alert, and GSA only picks one from the list to show up in the options.

Feign Death does not currently have any combat log data associated with it, so I can't check it without adding additional functionality. However, Survival Tactics (the PvP talent that buffs Feign Death) is in. I believe that is under "Buff Applied", and should say "Feign Dispel".
