### ISSUE TITLE
Poly "YOU" functionality 

### ISSUE THREAD

**Issue by devfel** [Rhykes/GladiatorlosSA2#4]
I remember from the old version that there was an addition of the word "YOU" when an enemy Polymorph or other spells like repentance was targeting your character. Can't seem to find a way to add this kind of voice information. 
Is it possible to add this to the new version?
This is super useful to Druids, Warrior, Priest, Shammys and other classes to use anti CC spells, like spell shapeshift, reflect, death or ghost wolf only if the CC is targeting your own character.

**Comment by Rhykes** [comment]
As far as I am aware, this is no longer possible. I've been looking for ways to achieve this but none are reliable. The combat log does not provide the information necessary to know for certain what the target is, and using the enemy's target is extremely unreliable due to the prevalence of mouseover/focus/a123 macros.

If I find a way to accomplish this, I will definitely look into adding it. For now, I'm afraid not, sorry!
