### ISSUE TITLE
Missing Spells

### ISSUE THREAD

**Issue by Moki182** [Rhykes/GladiatorlosSA2#5]
Hi

Im playing with the TBC classic version but the warlock's pet abilites are missing.
I tried adding it manually with the correct spell ID-s but I was not successful.

Could you add them for me? :)
-Spell Lock
-Devour Magic

Also the "PvP Trinketed Class" Feature is not working, could you check on it? 

Thx

See ya later ^^

**Comment by Rhykes** [comment]
Unfortunately I do not play TBC so it is very hard for me to test things like this and figure out what might be going on. If you adding the correct spellIDs did not seem to fix the issue, it will require a bit more investigation which means I need to find someone willing to test or get enough data from someone else.

If at all possible, please configure your combat log with a new filter with EVERYTHING enabled. Have a warlock use Spell Lock and Devour Magic on you, and send me a screenshot of what the log says. Sending me the IDs would help too, but I can fish for that off of WoWhead.

As for the trinket issue, this seems to be a problem on Blizzard's end with Trinket usage not being logged in the combat log. Apparently other addons have workarounds for this, but again since I don't play TBC I have no way to conceive of or test possible solutions. I'd recommend submitting a bug report to Blizzard telling them that the PvP trinkets do not properly show up in the combat log, so addons cannot track them through normal means. If that ever gets fixed, it should work automatically. Otherwise the best we can hope for is someone who plays TBC figuring out the solution and opening a pull request.
